name: ChunkClaim
main: naterich2.ChunkClaim.ChunkClaim
version: 1
commands:
  claim:
    description: This command claims the chunk the player is standing on
    usage: claim
    permission: ChunkClaim.claim
  abandon: 
    description: This command drops the chunk that the player has claimed
    usage: abondon
    permission: ChunkClaim.abandon
  strike:
  	description: This command strikes a player
  	usage: strike player
  	permission: ChunkClaim.strike  
permissions:
  ChunkClaim.*:
    description: Gives access to all claim and aclaim commands
    children:
      ChunkClaim.claim: true
      ChunkClaim.aclaim: true
      ChunkClaim.strike: true
  ChunkClaim.claim:
    description: Gives access to claim command
    default: true
  ChunkClaim.abandon:
    description: Gives access to abandon command
    default: true
  ChunkClaim.strike:
    description: Gives access to strike command
    default: op            
